#! /bin/sh

CFGFILE="$1"
EXTRACT="$2"
#
# extract.pike [arguments] infile(s)
#
#  Arguments: --project=name  default: first found in infile
#             --config=file   default: [project].xml
#             --out=file      default: [project]_eng.xml
#             --nocopy        update infile instead of infile.new
#             --notime        don't include dump time in xml files
#             --wipe          remove unused ids from xml
#             --sync          synchronize all locale projects
#             --encoding=enc  default: ISO-8859-1
#             --verbose       more informative text in xml
#
echo "  Rebuilding $CFGFILE"
$EXTRACT --config=$CFGFILE --wipe --sync --notime
