<include file=nav_shadow.inc>

<formoutput quote=¤>
  <textstyle $$nav_align$$ font='$$nav_font$$ $$nav_font_style$$'
    scale=$$nav_size$$ xspacing=5 yspacing=5>

  <boxstyle middle text bg=$$nav_bg_color$$ fg=$$nav_text_color$$
    alpha=0 ¤shadow¤>
  <boxstyle middle text selected bg=$$nav_bg_color_sel$$
    fg=$$nav_text_color_sel$$ alpha=0 ¤shadow¤>
  <boxstyle middle text mouseover bg=$$nav_bg_color_mouse$$
    fg=$$nav_text_color_mouse$$ alpha=0 ¤shadow_mouse¤>
</formoutput>