.TH ROXEN 8 "2009-05-07" "Roxen WebServer" "Roxen commands"

.SH NAME
roxen-create-server \- Creates a Roxen WebServer configuration interface

.SH SYNOPSIS

.PP
\fBroxen-create-server\fR [options]...

.SH SUMMARY

.PP
This command is interactive and creates a Roxen WebServer
configuration interface.

.SH OPTIONS

.TP
\fB--help\fR, \fB-h\fR
Display help information.

.TP
\fB--roxen-dir\fR=\fIdir\fR
Sets roxen directory.

.SH COPYRIGHT
Copyright \(co 2005 - 2009 Roxen Internet Software

.SH "SEE ALSO"
roxen
